import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>IYBC - Registration</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="homeregist-section">
        <div>
          <div className="wrapper">
            <div className="text-center">
              <h1 className="mx-auto text-sm md:text-lg lg:text-5xl">
                REGISTRATION FORM
              </h1>
              <h3 className="mx-auto mt-5 mb-2 text-sm md:text-lg lg:text-2xl">
                Choose Categories Participant for Registration IYBC 2025
              </h3>
            </div>
          </div>
          <div className="link-web mx-auto text-center">
            <a
              href="/registration/homeindo"
              className="btn btn-action text-center me-lg-5 m-2"
            >
              Indonesia Participant{" "}
              <i className="fa-solid fa-earth-americas"></i>
            </a>
            <a
              href="/registration/homeinter"
              className="btn btn-action text-center me-lg-5 m-2"
            >
              International Participant{" "}
              <i className="fa-solid fa-earth-americas"></i>
            </a>
            <br />
            <br />
            <a href="https://iybc.or.id/">
              <strong>back to main website</strong>
            </a>
          </div>
        </div>
      </section>
    </>
  );
}
